# Generated by Django 4.2.7 on 2023-12-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliases', models.CharField(max_length=255, unique=True)),
                ('column_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('customer_unique_id', models.CharField(max_length=32)),
                ('customer_city', models.CharField(max_length=255)),
                ('customer_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('zip_code_prefix', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('geolocation_lat', models.FloatField()),
                ('geolocation_lng', models.FloatField()),
                ('geolocation_city', models.CharField(max_length=255)),
                ('geolocation_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('order_status', models.CharField(max_length=20)),
                ('order_purchase_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order_approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_carrier_date', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_customer_date', models.DateTimeField(blank=True, null=True)),
                ('order_estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(db_column='zip_code_prefix', on_delete=django.db.models.deletion.CASCADE, to='olist_view.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('product_category_name', models.CharField(max_length=255)),
                ('product_name_length', models.IntegerField(blank=True, null=True)),
                ('product_description_length', models.IntegerField(blank=True, null=True)),
                ('product_photos_qty', models.IntegerField(blank=True, null=True)),
                ('product_weight_g', models.IntegerField(blank=True, null=True)),
                ('product_length_cm', models.IntegerField(blank=True, null=True)),
                ('product_height_cm', models.IntegerField(blank=True, null=True)),
                ('product_width_cm', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('product_category_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('product_category_name_english', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('seller_city', models.CharField(max_length=255)),
                ('seller_state', models.CharField(max_length=2)),
                ('zip_code_prefix', models.ForeignKey(db_column='zip_code_prefix', on_delete=django.db.models.deletion.CASCADE, to='olist_view.geolocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=32)),
                ('review_score', models.IntegerField(blank=True, null=True)),
                ('review_creation_date', models.DateTimeField()),
                ('review_answer_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='olist_view.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sequential', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_installments', models.IntegerField(blank=True, null=True)),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='olist_view.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField(blank=True, null=True)),
                ('shipping_limit_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='olist_view.order')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='olist_view.product')),
                ('seller_id', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, to='olist_view.seller')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code_prefix',
            field=models.ForeignKey(db_column='zip_code_prefix', on_delete=django.db.models.deletion.CASCADE, to='olist_view.geolocation'),
        ),
    ]
