# Generated by Django 4.2.7 on 2023-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=255)),
                ('search_text', models.CharField(max_length=255)),
            ],
        ),
    ]
