# Generated by Django 4.2.7 on 2023-11-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=32, unique=True)),
                ('customer_unique_id', models.CharField(max_length=32, unique=True)),
                ('customer_zip_code_prefix', models.CharField(max_length=10)),
                ('customer_city', models.CharField(max_length=255)),
                ('customer_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_zip_code_prefix', models.IntegerField()),
                ('geolocation_lat', models.FloatField()),
                ('geolocation_lng', models.FloatField()),
                ('geolocation_city', models.CharField(max_length=255)),
                ('geolocation_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('order_item_id', models.IntegerField()),
                ('product_id', models.CharField(max_length=32)),
                ('seller_id', models.CharField(max_length=32)),
                ('shipping_limit_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('payment_sequential', models.IntegerField()),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_installments', models.IntegerField()),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=32)),
                ('order_id', models.CharField(max_length=32)),
                ('review_score', models.IntegerField()),
                ('review_comment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('review_comment_message', models.TextField(blank=True, null=True)),
                ('review_creation_date', models.DateTimeField()),
                ('review_answer_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('customer_id', models.CharField(max_length=32)),
                ('order_status', models.CharField(max_length=20)),
                ('order_purchase_timestamp', models.DateTimeField()),
                ('order_approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_carrier_date', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_customer_date', models.DateTimeField(blank=True, null=True)),
                ('order_estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, unique=True)),
                ('product_category_name', models.CharField(max_length=255)),
                ('product_name_length', models.IntegerField()),
                ('product_description_length', models.IntegerField()),
                ('product_photos_qty', models.IntegerField()),
                ('product_weight_g', models.IntegerField()),
                ('product_length_cm', models.IntegerField()),
                ('product_height_cm', models.IntegerField()),
                ('product_width_cm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=255, unique=True)),
                ('product_category_name_english', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=32, unique=True)),
                ('seller_zip_code_prefix', models.CharField(max_length=10)),
                ('seller_city', models.CharField(max_length=255)),
                ('seller_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
