# Generated by Django 4.2.7 on 2023-12-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0002_publicdashboards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicdashboards',
            unique_together={('dashboard_name', 'search_text')},
        ),
    ]
