# Generated by Django 4.2.7 on 2023-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_unique_id',
            field=models.CharField(max_length=32),
        ),
    ]
