# Generated by Django 4.2.7 on 2023-12-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0003_alter_publicdashboards_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_order_id',
            field=models.ForeignKey(db_column='orderitem_order_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='olist_view.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_product_id',
            field=models.ForeignKey(db_column='orderitem_product_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='olist_view.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_seller_id',
            field=models.ForeignKey(db_column='orderitem_seller_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='olist_view.seller'),
        ),
    ]
