# Generated by Django 4.2.7 on 2023-11-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0004_alter_customer_customer_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('customer_id', models.CharField(max_length=32)),
                ('order_status', models.CharField(max_length=20)),
                ('order_purchase_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order_approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_carrier_date', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_customer_date', models.DateTimeField(blank=True, null=True)),
                ('order_estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
