# Generated by Django 4.2.7 on 2023-11-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0005_order_rename_sellers_seller_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_approved_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_delivered_carrier_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_delivered_customer_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_purchase_timestamp',
        ),
    ]
