# Generated by Django 4.2.7 on 2023-11-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0006_remove_order_order_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivered_carrier_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivered_customer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_purchase_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
