# Generated by Django 4.2.7 on 2023-12-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0007_eurusdforex_gamestopstockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStopAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliases', models.CharField(max_length=255, unique=True)),
                ('column_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
            ],
        ),
    ]
