# Generated by Django 4.2.7 on 2023-11-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist_view', '0007_order_order_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name_length',
            field=models.IntegerField(default=0),
        ),
    ]
